export const dummyData = [
  {
    id: 1,
    scientificName: 'Rosa rubiginosa',
    commonName: 'Sweet Briar',
    family: 'Rosaceae',
    origin: 'Europe',
    plantType: 'Perennial',
    growthHabit: 'Shrub',
    size: '1-3 meters',
    lightRequirements: 'Full Sun',
    soilRequirements: 'Well-drained, fertile',
    waterRequirements: 'Moderate',
    temperatureHumidity: '15-25°C, Moderate humidity',
    fertilization: 'Monthly during growing season',
    propagationMethods: 'Cuttings, Seeds',
    pestsDiseases: 'Aphids, Powdery mildew',
    pruningMaintenance: 'Prune after flowering',
    uses: 'Ornamental, Medicinal',
    specialNotes: 'Attracts bees',
    tags: ['Flowering', 'Fragrant'],
    recentObservations: [
      {
        date: '2024-07-20',
        details: 'Healthy growth, new flowers blooming',
        tags: ['Flowering'],
      },
    ],
    imageUri:
      'https://upload.wikimedia.org/wikipedia/commons/4/42/Wild_Rosa_rubiginosa.jpg',
  },
  {
    id: 2,
    scientificName: 'Ficus lyrata',
    commonName: 'Fiddle Leaf Fig',
    family: 'Moraceae',
    origin: 'West Africa',
    plantType: 'Perennial',
    growthHabit: 'Tree',
    size: '10-15 meters',
    lightRequirements: 'Bright, indirect light',
    soilRequirements: 'Well-drained, loamy',
    waterRequirements: 'Moderate',
    temperatureHumidity: '18-24°C, High humidity',
    fertilization: 'Bi-monthly during growing season',
    propagationMethods: 'Cuttings',
    pestsDiseases: 'Spider mites, Leaf spot',
    pruningMaintenance: 'Prune to maintain shape',
    uses: 'Ornamental',
    specialNotes: 'Can be toxic to pets',
    tags: ['Indoor', 'Low Maintenance'],
    recentObservations: [
      {
        date: '2024-07-18',
        details: 'Leaves looking healthy',
        tags: ['Healthy'],
      },
    ],
    imageUri:
      'https://fiddleleaffigplant.com/wp-content/uploads/2020/11/image5.jpg',
  },
];
